### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by shirishag75** [makrohn/concordia#3]
There is no audio when playing the game :-

$ ./concordia
No joysticks were found.
Using joystick #0.
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
ignoring unknown key multiplier set to 300
ignoring unknown key multiplier set to 150
PowerManager sfx: Loading sound ./soundfx/powers/potion.ogg (soundfx/powers/potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager open tab: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager close tab: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
LootManager dropping loot: Loading sound ./soundfx/flying_loot.ogg (soundfx/flying_loot.ogg) failed: Mix_LoadWAV_RW with NULL src 
Unable to open /home/shirish/.local/share/concordia/stash.txt!
Avatar melee attack: Loading sound ./soundfx/melee_attack.ogg (soundfx/melee_attack.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar was hit: Loading sound ./soundfx/femaledark_hit.ogg (soundfx/femaledark_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar death: Loading sound ./soundfx/femaledark_die.ogg (soundfx/femaledark_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar blocking: Loading sound ./soundfx/powers/block.ogg (soundfx/powers/block.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical attack sound: Loading sound ./soundfx/enemies/bee_phys.ogg (soundfx/enemies/bee_phys.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager mental attack sound: Loading sound ./soundfx/enemies/bee_ment.ogg (soundfx/enemies/bee_ment.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical hit sound: Loading sound ./soundfx/enemies/bee_hit.ogg (soundfx/enemies/bee_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager die sound: Loading sound ./soundfx/enemies/bee_die.ogg (soundfx/enemies/bee_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager critdeath sound: Loading sound ./soundfx/enemies/bee_critdie.ogg (soundfx/enemies/bee_critdie.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth1.ogg (soundfx/steps/step_cloth1.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth2.ogg (soundfx/steps/step_cloth2.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth3.ogg (soundfx/steps/step_cloth3.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth4.ogg (soundfx/steps/step_cloth4.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
ignoring unknown key multiplier set to 300
ignoring unknown key multiplier set to 150
PowerManager sfx: Loading sound ./soundfx/powers/potion.ogg (soundfx/powers/potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager open tab: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager close tab: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
LootManager dropping loot: Loading sound ./soundfx/flying_loot.ogg (soundfx/flying_loot.ogg) failed: Mix_LoadWAV_RW with NULL src 
Couldn't load portrait: Couldn't open ./images/portraits/male01.png
Avatar melee attack: Loading sound ./soundfx/melee_attack.ogg (soundfx/melee_attack.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar was hit: Loading sound ./soundfx/male_hit.ogg (soundfx/male_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar death: Loading sound ./soundfx/male_die.ogg (soundfx/male_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar blocking: Loading sound ./soundfx/powers/block.ogg (soundfx/powers/block.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar melee attack: Loading sound ./soundfx/melee_attack.ogg (soundfx/melee_attack.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar was hit: Loading sound ./soundfx/femaledark_hit.ogg (soundfx/femaledark_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar death: Loading sound ./soundfx/femaledark_die.ogg (soundfx/femaledark_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar blocking: Loading sound ./soundfx/powers/block.ogg (soundfx/powers/block.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical attack sound: Loading sound ./soundfx/enemies/bee_phys.ogg (soundfx/enemies/bee_phys.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager mental attack sound: Loading sound ./soundfx/enemies/bee_ment.ogg (soundfx/enemies/bee_ment.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical hit sound: Loading sound ./soundfx/enemies/bee_hit.ogg (soundfx/enemies/bee_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager die sound: Loading sound ./soundfx/enemies/bee_die.ogg (soundfx/enemies/bee_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager critdeath sound: Loading sound ./soundfx/enemies/bee_critdie.ogg (soundfx/enemies/bee_critdie.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth1.ogg (soundfx/steps/step_cloth1.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth2.ogg (soundfx/steps/step_cloth2.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth3.ogg (soundfx/steps/step_cloth3.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth4.ogg (soundfx/steps/step_cloth4.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
ignoring unknown key multiplier set to 300
ignoring unknown key multiplier set to 150
PowerManager sfx: Loading sound ./soundfx/powers/potion.ogg (soundfx/powers/potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
No item sets were found.
ItemManager books: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager cloths: Loading sound ./soundfx/inventory/inventory_cloth.ogg (soundfx/inventory/inventory_cloth.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager coins: Loading sound ./soundfx/inventory/inventory_coins.ogg (soundfx/inventory/inventory_coins.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager gems: Loading sound ./soundfx/inventory/inventory_gem.ogg (soundfx/inventory/inventory_gem.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager leather: Loading sound ./soundfx/inventory/inventory_leather.ogg (soundfx/inventory/inventory_leather.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager metal: Loading sound ./soundfx/inventory/inventory_metal.ogg (soundfx/inventory/inventory_metal.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager page: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager maille: Loading sound ./soundfx/inventory/inventory_maille.ogg (soundfx/inventory/inventory_maille.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager objects: Loading sound ./soundfx/inventory/inventory_object.ogg (soundfx/inventory/inventory_object.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager heavy: Loading sound ./soundfx/inventory/inventory_heavy.ogg (soundfx/inventory/inventory_heavy.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager wood: Loading sound ./soundfx/inventory/inventory_wood.ogg (soundfx/inventory/inventory_wood.ogg) failed: Mix_LoadWAV_RW with NULL src 
ItemManager potions: Loading sound ./soundfx/inventory/inventory_potion.ogg (soundfx/inventory/inventory_potion.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager open tab: Loading sound ./soundfx/inventory/inventory_page.ogg (soundfx/inventory/inventory_page.ogg) failed: Mix_LoadWAV_RW with NULL src 
MenuManager close tab: Loading sound ./soundfx/inventory/inventory_book.ogg (soundfx/inventory/inventory_book.ogg) failed: Mix_LoadWAV_RW with NULL src 
LootManager dropping loot: Loading sound ./soundfx/flying_loot.ogg (soundfx/flying_loot.ogg) failed: Mix_LoadWAV_RW with NULL src 
Couldn't load portrait: Couldn't open ./images/portraits/male01.png
Avatar melee attack: Loading sound ./soundfx/melee_attack.ogg (soundfx/melee_attack.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar was hit: Loading sound ./soundfx/male_hit.ogg (soundfx/male_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar death: Loading sound ./soundfx/male_die.ogg (soundfx/male_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar blocking: Loading sound ./soundfx/powers/block.ogg (soundfx/powers/block.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar melee attack: Loading sound ./soundfx/melee_attack.ogg (soundfx/melee_attack.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar was hit: Loading sound ./soundfx/femaledark_hit.ogg (soundfx/femaledark_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar death: Loading sound ./soundfx/femaledark_die.ogg (soundfx/femaledark_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar blocking: Loading sound ./soundfx/powers/block.ogg (soundfx/powers/block.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical attack sound: Loading sound ./soundfx/enemies/bee_phys.ogg (soundfx/enemies/bee_phys.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager mental attack sound: Loading sound ./soundfx/enemies/bee_ment.ogg (soundfx/enemies/bee_ment.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager physical hit sound: Loading sound ./soundfx/enemies/bee_hit.ogg (soundfx/enemies/bee_hit.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager die sound: Loading sound ./soundfx/enemies/bee_die.ogg (soundfx/enemies/bee_die.ogg) failed: Mix_LoadWAV_RW with NULL src 
EnemyManager critdeath sound: Loading sound ./soundfx/enemies/bee_critdie.ogg (soundfx/enemies/bee_critdie.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth1.ogg (soundfx/steps/step_cloth1.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth2.ogg (soundfx/steps/step_cloth2.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth3.ogg (soundfx/steps/step_cloth3.ogg) failed: Mix_LoadWAV_RW with NULL src 
Avatar loading foot steps: Loading sound ./soundfx/steps/step_cloth4.ogg (soundfx/steps/step_cloth4.ogg) failed: Mix_LoadWAV_RW with NULL src 

I have no idea why there is no audio. 

Looking for update on the same.

**Comment by makrohn** [comment]
Are you actually not getting any audio, or just these warnings?  There's unfortunately a lot of hardcoded audio files in the engine right now, and they're working on removing all of those references.  It shouldn't interfere with the normal music and sound effects.

**Comment by shirishag75** [comment]
Not getting any audio at all :(

**Comment by makrohn** [comment]
Hmmm.  I have no idea, either.  Can you check with the latest flare-game build and see if you're running into the same issue with flare-game?

**Comment by shirishag75** [comment]
I updated and played with flare, no issues in the game there in respect of audio or anything else.

**Comment by makrohn** [comment]
Hmm.  Not even any sound effects?  Do you mind posting your settings.txt? (~/.config/concordia/settings.txt in Ubuntu)  What OS are you running?

**Comment by makrohn** [comment]
In another attempt at troubleshooting, you could also drag and drop the "mods/concordia" mod folder into your flare-game mods folder, enable "concordia" mod and disable the others, and see if you get sound.  You won't have access to your normal concordia saves, but it might help us nail down whether it's the mod folder or the binary.

**Comment by shirishag75** [comment]
umm... here it is :-

~/.config/concordia$ cat settings.txt 

# fullscreen mode. 1 enable, 0 disable.

fullscreen=0

# display resolution. 640x480 minimum.

resolution_w=1024
resolution_h=768

# Enable music and sound subsystem.

audio=1

# music and sound volume (0 = silent, 128 = max)

music_volume=128
sound_volume=128

# display floating damage text. 1 enable, 0 disable.

combat_text=1

# use mouse to move (experimental). 1 enable, 0 disable.

mouse_move=0

# hardware surfaces, double buffering. Try disabling for performance. 1 enable, 0 disable.

hwsurface=0
doublebuf=0

# animated tiles. Try disabling for performance. 1 enable, 0 disable.

animated_tiles=1

# joystick settings.

enable_joystick=0
joystick_device=0

# 2-letter language code.

language=en

# allow changing gamma (experimental). 1 enable, 0 disable.

change_gamma=0

# screen gamma (0.5 = darkest, 2.0 = lightest)

gamma=1

# texture quality (0 = low quality, 1 = high quality)

texture_quality=1

# use mouse to aim. 1 enable, 0 disable.

mouse_aim=1

# show frames per second. 1 enable, 0 disable.

show_fps=1

I was able to resolve the issue by upgrading the pulseaudio server to the one in Debian experimental. 

$ apt-show-versions -a pulseaudio
pulseaudio 2.1-2 install ok installed
pulseaudio 0.9.21-3+squeeze1 stable       ftp.debian.org
pulseaudio 2.0-6             wheezy       ftp.debian.org
pulseaudio 2.0-6             unstable     ftp.debian.org
pulseaudio 2.1-2             experimental ftp.debian.org
pulseaudio/experimental uptodate 2.1-2

The issue was with the one in unstable, in experimental it works.
