### ISSUE TITLE
not able to attach the dagger either to rmb or wear it in the inventory

### ISSUE THREAD

**Issue by shirishag75** [makrohn/concordia#5]
hi all, 
dunno if it's a bug or not. I have a dagger in the inventory but not able to wear it or have it being used as right mouse button or anything. 

Even where the inventory appears seems to be stuck and I can't seem to be able to manipulate it on the screen . So it's two bugs but one more than the other.

**Comment by makrohn** [comment]
Hmm.  Works fine for me...  can you double-check that concordia is your only activated mod in the configuration screen?

**Comment by shirishag75** [comment]
I only have concordia in the activated mod. I don't have anything else either in activated mods or anything for that matter in Available mods.

**Comment by shirishag75** [comment]
closing it as the documentation tells the changed scenario. Basically I was trying to play ./concordia when I should be playing ./flare with concordia as the only available and activated mod here :)
